AllCops:
  Exclude:
    - vendor/**/*

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
